name: :new: Feature Request
description: Request a new feature
labels: ['feature']
title: '[FEAT]: Name'

body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Give a brief description of the feature you would like to do
    validations:
      required: true

  - type: textarea
    id: additional-information
    attributes:
      label: Additional Information
      description: Give some additional information on the feature request like proposed solutions, links, screenshots, etc.