name: Add features to features project

on:
  workflow_call:
  
env:
  TOKEN: ${{secrets.AUTO_ADD_ISSUE}}

jobs:
  add-to-project:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      
    steps:
    - uses: actions/checkout@v3
    
    - uses: actions/add-to-project@v0.4.0
      with:
        project-url: https://github.com/orgs/splitscale/projects/1
        github-token: $TOKEN
        labeled: feature
        label-operator: OR
