name: Auto Assign to Project(s)

on:
  issues:
    types: [opened, labeled]

env:
  MY_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}

jobs:
  assign_one_project:
    runs-on: ubuntu-latest
    name: Assign to One Project
    steps:
    - name: Assign to One Project
      uses: srggrs/assign-one-project-github-action@1.3.1
      with:
        # The url of the project to be assigned to.
        project: https://github.com/orgs/splitscale/projects/1
        # The column name of the project, defaults to "To do" for issues and "In progress" for pull requests.
        column_name: "🆕 New"
