name: Add features to features project

on:
  workflow_call:
  issues:
    types:
      - opened

env:
  MY_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}

jobs:
  add-to-project:
    runs-on: ubuntu-latest
    steps:
    - name: Add To GitHub projects
      uses: actions/add-to-project@v0.4.0
      with: 
        # URL of the project to add issues to
        project-url: https://github.com/orgs/splitscale/projects/1/views/1
        # A GitHub personal access token with write access to the project
        github-token: MY_GITHUB_TOKEN
        # A comma-separated list of labels to use as a filter for issue to be added
        labeled: feature
        # The behavior of the labels filter, AND to match all labels, OR to match any label, NOT to exclude any listed label (default is OR)
        label-operator: OR
