name: Auto Assign to Project(s)

on:
  issues:
    types: [opened, labeled]

env:
  MY_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}

jobs:
  assign_one_project:
    runs-on: ubuntu-latest
    name: Assign to One Project
    steps:
    - name: Assign issues and pull requests with `bug` label to project 1
      uses: srggrs/assign-one-project-github-action@1.3.1
      if: github.event.action == 'opened' && contains(github.event.issue.labels.*.name, 'feature')
      with:
        # The url of the project to be assigned to.
        project: https://github.com/orgs/splitscale/projects/1
